spring:
  application:
    name: reactive-demo

management:
  info:
    git:
      mode: full

server:
  port: 8081

logging:
  level:
    root: warn
    com.github.edeandrea.reactivedemo: debug
    com.mycompany.myframework: debug

mycompany:
  myframework:
    config:
      enable-actuators: true
      security:
        enabled: true
