spring:
  application:
    name: servlet-demo

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

logging:
  level:
    root: warn
    com.github.edeandrea.servletdemo: debug
    com.mycompany.myframework: debug

springfox:
  documentation:
    swagger:
      v2:
        path: /api

mycompany:
  myframework:
    config:
      enable-actuators: true
      security:
        enabled: true
        cors:
          allowed-domains: subdomain.redhat.com
    tracing:
      enable-response-headers: true
